FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0

LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"
LABEL org.opencontainers.image.description="SWIM DNOTAM Provider Validator — UI and mTLS proxy to exercise DNOTAM provider APIs; AMQP message capture (ex swim-dnotam-mockclient)."
LABEL org.opencontainers.image.version="0.0.1"

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --chown=1001:root --chmod=0755 target/*-runner /work/application

EXPOSE 8080
EXPOSE 8443
EXPOSE 9000

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]

