apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: swim-dnotam-provider-validator
  labels:
    app: swim-dnotam-provider-validator
    app.kubernetes.io/name: swim-dnotam-provider-validator
    app.kubernetes.io/component: dnotam-provider-validator
    app.kubernetes.io/part-of: swim-dnotam
    app.kubernetes.io/singleton: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: swim-dnotam-provider-validator
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

