apiVersion: v1
kind: Secret
metadata:
  name: swim-dnotam-provider-validator-passwords
  labels:
    app: swim-dnotam-provider-validator
    app.kubernetes.io/name: swim-dnotam-provider-validator
    app.kubernetes.io/component: dnotam-provider-validator
    app.kubernetes.io/part-of: swim-dnotam
type: Opaque
stringData:
  password: changeit
  PROXY_MTLS_KEYSTORE_PASSWORD: changeit
  PROXY_MTLS_TRUSTSTORE_PASSWORD: changeit
